// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaJrcrbQX5U5CIFu7uHr1N-HFI9Bn-VBc',
    appId: '1:157327220949:web:02bcf1a1fc4302c18c025c',
    messagingSenderId: '157327220949',
    projectId: 'data-8022f',
    authDomain: 'data-8022f.firebaseapp.com',
    storageBucket: 'data-8022f.appspot.com',
    measurementId: 'G-DYQW8VN6P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDG6dL3FggyLdXK-8U-13rkloCnpNdYTM',
    appId: '1:157327220949:android:45a545e6bfe9b3b08c025c',
    messagingSenderId: '157327220949',
    projectId: 'data-8022f',
    storageBucket: 'data-8022f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxoE66dvxDBNk_RjccIto-eesrX8jolCA',
    appId: '1:157327220949:ios:ecf30a3bdaa3f8538c025c',
    messagingSenderId: '157327220949',
    projectId: 'data-8022f',
    storageBucket: 'data-8022f.appspot.com',
    iosBundleId: 'com.example.database',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxoE66dvxDBNk_RjccIto-eesrX8jolCA',
    appId: '1:157327220949:ios:ecf30a3bdaa3f8538c025c',
    messagingSenderId: '157327220949',
    projectId: 'data-8022f',
    storageBucket: 'data-8022f.appspot.com',
    iosBundleId: 'com.example.database',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaJrcrbQX5U5CIFu7uHr1N-HFI9Bn-VBc',
    appId: '1:157327220949:web:b8640ad17b6a7c1a8c025c',
    messagingSenderId: '157327220949',
    projectId: 'data-8022f',
    authDomain: 'data-8022f.firebaseapp.com',
    storageBucket: 'data-8022f.appspot.com',
    measurementId: 'G-T299ZC5GT4',
  );
}
